In [10]:
import pandas as pd
import random
lst = ['robot'] * 10
lst += ['human'] * 10
random.shuffle(lst)
data = pd.DataFrame({'whoAmI':lst})
data.head()
print(data)

   whoAmI
0   human
1   human
2   human
3   robot
4   human
5   human
6   robot
7   robot
8   human
9   robot
10  human
11  robot
12  robot
13  human
14  human
15  robot
16  robot
17  human
18  robot
19  robot

In [11]:
data.loc[data["whoAmI"] == "human", "whoAmI"] = True
data.loc[data["whoAmI"] != True, "whoAmI"] = False

data

   whoAmI
0    True
1    True
2    True
3   False
4    True
5    True
6   False
7   False
8    True
9   False
10   True
11  False
12  False
13   True
14   True
15  False
16  False
17   True
18  False
19  False